name: Custom Reviewer Notification for Slack

on:
  pull_request:
    branches:
      - '**'
    types: [assigned, review_requested]

jobs:
  notify_slack:
    runs-on: ubuntu-latest
    steps:
      - name: Notify All Reviewers
        run: |
          PR_URL="${{ github.event.pull_request.html_url }}"
          PR_TITLE="${{ github.event.pull_request.title }}"
          ASSIGNEE="${{ github.event.pull_request.assignee.login }}"
          SLACK_WEBHOOK_URL="${{ secrets.SLACK_WEBHOOK_URL }}"
          REVIEWERS_JSON="${{ toJson(github.event.pull_request.requested_reviewers) }}"
          
          echo "Reviewers JSON: $REVIEWERS_JSON"
          
          FIXED_JSON=$(echo "$REVIEWERS_JSON" | jq 'map({
            avatar_url: .avatar_url,
            events_url: .events_url,
            followers_url: .followers_url,
            following_url: .following_url,
            gists_url: .gists_url,
            gravatar_id: .gravatar_id,
            html_url: .html_url,
            id: .id,
            login: .login,
            node_id: .node_id,
            organizations_url: .organizations_url,
            received_events_url: .received_events_url,
            repos_url: .repos_url,
            site_admin: .site_admin,
            starred_url: .starred_url,
            subscriptions_url: .subscriptions_url,
            type: .type,
            url: .url
          })')
          echo "$FIXED_JSON" | jq .

