name: Custom Reviewer Notification for Slack

on:
  pull_request:
    branches:
      - '**'
    types: [assigned, review_requested]
jobs:
  notify_slack:
    runs-on: ubuntu-latest
    steps:
      - name: Display JSON
        run: |
          PR_URL="${{ github.event.pull_request.html_url }}"
          PR_TITLE="${{ github.event.pull_request.title }}"
          ASSIGNEE="${{ github.event.pull_request.assignee.login }}"
          SLACK_WEBHOOK_URL="${{ secrets.SLACK_WEBHOOK_URL }}"
          REVIEWERS_JSON="${{ toJson(github.event.pull_request.requested_reviewers) }}"
          
          echo "Reviewers JSON: $REVIEWERS_JSON"

          # Încercăm să afișăm JSON-ul direct cu jq pentru a vedea eroarea
          echo "$REVIEWERS_JSON" | jq .
