name: Custom Reviewer Notification for Slack

on:
  pull_request:
    branches:
      - '**'
    types: [assigned, review_requested]

jobs:
  notify_slack:
    runs-on: ubuntu-latest
    steps:
      - name: Notify All Reviewers
        run: |
          PR_URL="${{ github.event.pull_request.html_url }}"
          PR_TITLE="${{ github.event.pull_request.title }}"
          ASSIGNEE="${{ github.event.pull_request.assignee.login }}"
          SLACK_WEBHOOK_URL="${{ secrets.SLACK_WEBHOOK_URL }}"
          REVIEWERS_JSON="${{ toJson(github.event.pull_request.requested_reviewers) }}"

          PAYLOAD=$(jq -n \
                    --arg pr_url "$PR_URL" \
                    --arg pr_title "$PR_TITLE" \
                    --arg assignee "$ASSIGNEE" \
                    --arg reviewers "$REVIEWERS_JSON" \
                    '{
                      "text": "New Assignment on PR!",
                      "attachments": [
                        {
                          "color": "#36a64f",
                          "fields": [
                            {"title": "Assigned to", "value": $assignee, "short": false},
                            {"title": "Reviewers", "value": $reviewers, "short": false},
                            {"title": "PR Title", "value": $pr_title, "short": false},
                            {"title": "PR URL", "value": $pr_url, "short": false}
                          ]
                        }
                      ]
                    }')

          curl -X POST -H 'Content-type: application/json' --data "$PAYLOAD" $SLACK_WEBHOOK_URL
