name: Custom Reviewer Notification for Slack

on:
  pull_request:
    branches:
      - '**'
    types: [assigned, review_requested]

jobs:
  notify_slack:
    runs-on: ubuntu-latest
    steps:
      - name: Notify All Reviewers
        run: |
          
          PR_URL="${{ github.event.pull_request.html_url }}"
          PR_TITLE="${{ github.event.pull_request.title }}"
          ASSIGNEE="${{ github.event.pull_request.assignee.login }}"
          SLACK_WEBHOOK_URL="${{ secrets.SLACK_WEBHOOK_URL }}"
          REVIEWERS_JSON="${{ toJson(github.event.pull_request.requested_reviewers) }}"
          curl -X POST -H 'Content-type: application/json' --data '{"text": "New Assignment on PR!", "attachments": [{"color": "#36a64f", "fields": [{"title": "Assigned to", "value": "'$ASSIGNEE'", "short": false}, {"title": "Reviewers", "value": "'$REVIEWERS_JSON'", "short": false}, {"title": "PR Title", "value": "'$PR_TITLE'", "short": false}, {"title": "PR URL", "value": "'$PR_URL'", "short": false}]}]}' $SLACK_WEBHOOK_URL
