name: Custom Reviewer Notification for Slack

on:
  pull_request:
    branches:
      - '**'
    types: [assigned, review_requested]
# Ajustăm scriptul pentru a asigura parsarea corectă a JSON-ului
jobs:
  notify_slack:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Reviewers
        run: |
          PR_URL="${{ github.event.pull_request.html_url }}"
          PR_TITLE="${{ github.event.pull_request.title }}"
          ASSIGNEE="${{ github.event.pull_request.assignee.login }}"
          SLACK_WEBHOOK_URL="${{ secrets.SLACK_WEBHOOK_URL }}"
          REVIEWERS_JSON="${{ toJson(github.event.pull_request.requested_reviewers) }}"

          # Adăugăm ghilimele în jurul tuturor valorilor string din JSON
          FIXED_JSON=$(echo "$REVIEWERS_JSON" | 
            jq 'map(with_entries(.value |= if type=="string" then "\"\(. + "\"")" else . end))')

          echo "Fixed JSON: $FIXED_JSON"

          # Procesăm JSON-ul pentru a extrage valorile de login
          echo "$FIXED_JSON" | jq -r '.[].login' | while read reviewer_login; do
            echo "Processing reviewer: $reviewer_login"
            # Aici puteți adăuga logica pentru a trimite notificări utilizând SLACK_WEBHOOK_URL
          done
