name: Custom Reviewer Notification for Slack

on:
  pull_request:
    branches:
      - '**'
    types: [assigned, review_requested]

jobs:
  notify_slack:
    runs-on: ubuntu-latest
    steps:
      - name: Show JSON
        run: |
          echo "Reviewers JSON: $REVIEWERS_JSON"
