name: Custom Reviewer Notification for Slack

on:
  pull_request:
    branches:
      - '**'
    types: [assigned, review_requested]

jobs:
  notify_slack:
    runs-on: ubuntu-latest
    steps:
      - name: Notify All Reviewers
        run: |
          PR_URL="${{ github.event.pull_request.html_url }}"
          PR_TITLE="${{ github.event.pull_request.title }}"
          ASSIGNEE="${{ github.event.pull_request.assignee.login }}"
          SLACK_WEBHOOK_URL="${{ secrets.SLACK_WEBHOOK_URL }}"
          REVIEWERS_JSON="${{ toJson(github.event.pull_request.requested_reviewers) }}"
          echo "Initial JSON: $REVIEWERS_JSON si gata"
          
          
          
               
    

          declare -A emailMap
          emailMap["andreit77"]="andrei.turcas@joinhandshake.com"
          emailMap["andreea-beatrice-manea"]="andreea.manea@joinhandshake.com"
          emailMap["bogdan-judele"]="bogdan.judele@joinhandshake.com"
          emailMap["bjudele"]="bogdan.judele@joinhandshake.com"
          emailMap["hsbogdant"]="bogdan.teslarasu@joinhandshake.com"
          emailMap["markohandshake"]="marko.ivanovic@joinhandshake.com"
          emailMap["irimia-roxana"]="roxana.irimia@joinhandshake.com"
          emailMap["victor-bratoiu"]="victor.bratoiu@joinhandshake.com"
          emailMap["bogdanjudelle"]="victor.bratoiu@joinhandshake.com"
          
           # Extragem și curățăm login-urile folosind awk și tr
          REVIEWER_LOGINS=$(echo "$REVIEWERS_JSON" | grep -oP '"login":\s*"\K[^"]+' | tr '\n' ' ')
          echo "Extracted Logins: $REVIEWER_LOGINS"     
          
           # Afișează cheile din emailMap
          echo "Available keys in emailMap:"
          for k in "${!emailMap[@]}"; do
            echo "$k - ${emailMap[$k]}"
          done
          
          # Procesăm fiecare login extras
          for login in $REVIEWER_LOGINS; do
            REVIEWER_EMAIL="${emailMap[$login]}"
            echo "Cautand emailul lui $login am gasit $REVIEWER_EMAIL"
            if [ ! -z "$REVIEWER_EMAIL" ]; then  # Verificăm dacă emailul există în map
              echo "Apelez webhook pentru $REVIEWER_EMAIL sau $login"
              PAYLOAD=$(jq -n \
                        --arg pr_url "$PR_URL" \
                        --arg pr_title "$PR_TITLE" \
                        --arg assignee "$ASSIGNEE" \
                        --arg reviewer_email "$REVIEWER_EMAIL" \
                        '{
                          "pr_url": $pr_url,
                          "assignee": $assignee,
                          "reviewer_email": $reviewer_email
                        }')
              curl -X POST -H 'Content-type: application/json' --data "$PAYLOAD" $SLACK_WEBHOOK_URL
              echo "Notified $login"
            else
              echo "No webhook call for $login - not found in emailMap"
            fi
          done