name: Custom Reviewer Notification for Slack

on:
  pull_request:
    branches:
      - '**'
    types: [assigned, review_requested]
jobs:
  notify_slack:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Specific Reviewers
        run: |
          PR_URL="${{ github.event.pull_request.html_url }}"
          PR_TITLE="${{ github.event.pull_request.title }}"
          ASSIGNEE="${{ github.event.pull_request.assignee.login }}"
          SLACK_WEBHOOK_URL="${{ secrets.SLACK_WEBHOOK_URL }}"
          REVIEWERS_JSON="${{ toJson(github.event.pull_request.requested_reviewers) }}"
          
          # Corectăm JSON-ul folosind sed pentru a adăuga ghilimelele necesare la toate valorile
          CORRECTED_JSON=$(echo "$REVIEWERS_JSON" |
            sed -r 's/:([^"])([^,}]*)/: "\1\2"/g' |  # Pune ghilimele în jurul valorilor
            sed 's/\\/\\\\/g' |                      # Escapare backslash
            sed 's/:\s*"/: "/g' |                    # Elimină spațiile după : și înainte de "
            sed 's/"\s*"/""/g' |                     # Elimină spațiile între ghilimele
            sed 's/\"https/https/g' |                # Corectează URL-urile
            sed 's/,\s*"/, "/g' |                    # Corectează spațiile după virgule
            sed 's/\\"/"/g')                         # Corectează escapările ghilimelelor
          
          echo "Corrected JSON: $CORRECTED_JSON"
          echo "$CORRECTED_JSON" | jq .
  
  
          declare -A emailMap
          emailMap["andreit77"]="andrei.turcas@joinhandshake.com"
          emailMap["andreea-beatrice-manea"]="andreea.manea@joinhandshake.com"
          emailMap["bogdan-judele"]="bogdan.judele@joinhandshake.com"
          emailMap["bjudele"]="bogdan.judele@joinhandshake.com"
          emailMap["hsbogdant"]="bogdan.teslarasu@joinhandshake.com"
          emailMap["markohandshake"]="marko.ivanovic@joinhandshake.com"
          emailMap["irimia-roxana"]="roxana.irimia@joinhandshake.com"
          emailMap["victor-bratoiu"]="victor.bratoiu@joinhandshake.com"
          
          # Procesăm JSON-ul corectat și notificăm doar reviewerii relevanți
          echo "$CORRECTED_JSON" | jq -c '.[]' | while IFS= read -r reviewer; do
            REVIEWER_USERNAME=$(echo "$reviewer" | jq -r '.login')
            REVIEWER_EMAIL="${emailMap[$REVIEWER_USERNAME]}"
            if [ ! -z "$REVIEWER_EMAIL" ]; then
              PAYLOAD=$(jq -n \
                        --arg pr_url "$PR_URL" \
                        --arg pr_title "$PR_TITLE" \
                        --arg assignee "$ASSIGNEE" \
                        --arg reviewer_email "$REVIEWER_EMAIL" \
                        '{
                          "pr_url": $pr_url,
                          "assignee": $assignee,
                          "reviewer_email": $reviewer_email
                        }')
              curl -X POST -H 'Content-type: application/json' --data "$PAYLOAD" $SLACK_WEBHOOK_URL
            fi
          done